name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Windows Specific Setup
      if: matrix.os == 'windows-latest'
      run: |
        curl -OLS https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311.exe
        .\wix311.exe /install /quiet /norestart
        choco install llvm
    - name: Build
      run: cargo build --verbose
